### ISSUE TITLE
运行发现错误

### ISSUE THREAD

**Issue by shiyaping2012** [onehaitao/Att-BLSTM-relation-extraction#1]
--------------------------------------
start to train the model ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'SemEvalDataLoader' object has no attribute '__collate_fn'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'SemEvalDataLoader' object has no attribute '__collate_fn'
Traceback (most recent call last):
  File "run.py", line 100, in <module>
    train(model, criterion, loader, config)
  File "run.py", line 37, in train
    for step, (data, label) in enumerate(train_loader):
  File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "C:\Program Files\Python36\l

**Comment by shiyaping2012** [comment]
经过我仔细研究发现，dataloader函数的参数 不识别私有变量__collate_fn,将其改为公司有的双下划线去掉即可。

**Comment by glMa7** [comment]
哇，试了一下果然，真厉害
