### ISSUE TITLE
TypeError: __collate_fn()

### ISSUE THREAD

**Issue by 6shuaishuai** [onehaitao/Att-BLSTM-relation-extraction#8]
python = 3.6
pytorch = 1.3.0
After python run.py, show this error massage

Traceback (most recent call last):
  File ".\run.py", line 105, in <module>
    train(model, criterion, loader, config)
  File ".\run.py", line 39, in train
    for step, (data, label) in enumerate(train_loader):
  File "C:\Users\90607\.conda\envs\Att-BLSTM-relation-extraction-master\lib\site-packages\torch\utils\data\dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\90607\.conda\envs\Att-BLSTM-relation-extraction-master\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
TypeError: __collate_fn() takes 1 positional argument but 2 were given

**Comment by onehaitao** [comment]
I think you can see this [issue](https://github.com/onehaitao/Att-BLSTM-relation-extraction/issues/7), maybe useful to you.
